export const UPLOAD_IMAGE_TEMP_DIR = 'uploads/images/temp'
export const UPLOAD_IMAGE_DIR = 'uploads/images'
export const UPLOAD_AVATAR_DIR = 'uploads/avatars'
export const UPLOAD_AVATAR_TEMP_DIR = 'uploads/avatars/temp'
export const UPLOAD_VIDEO_DIR = 'uploads/videos'
